### ISSUE TITLE
`ape.reverts()` fails when trying to decode reason

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape-optimism#12]
### Environment information

Latest ape
macOS

### What went wrong?

When using `ape.reverts()` on a reverted call, you get this error:

```
class 'OverflowError'> occurred: cannot fit 'int' into an index-sized integer
```

### How can it be fixed?

* Figure out the decoding differences and network differences and re-assess.

**Comment by unparalleled-js** [comment]
Realized this is because of this: https://github.com/ApeWorX/ape/pull/1247
We can copy similar logic if needed or else that PR may fix it here as well.
