### ISSUE TITLE
Optimism Plugin Breaks 

### ISSUE THREAD

**Issue by solarthesis** [ApeWorX/ape-optimism#29]
### Environment information

- `ape` and plugin versions:

```
$ ape --version
0.7.16

$ ape plugins list
WARNING: Unprocessed plugin config(s): optimism, hardhat. Plugins may not be installed yet or keys may be mis-spelled.
Installed Plugins
  alchemy      0.7.1
  etherscan    0.7.2
  hardhat      0.7.2
  optimism     0.7.3
  safe         0.7.0b2
  solidity     0.7.2
```

- Python Version: 3.9
- OS: macOS/linux/win ubuntu

### What went wrong?
optimism network does not install

Please include information like:

- what command you ran
installed eth-ape with pip, then installed the above packages, the result 
```
WARNING: Unprocessed plugin config(s): optimism, hardhat. Plugins may not be installed yet or keys may be mis-spelled.
Traceback (most recent call last):
  File "/app/main.py", line 53, in <module>
    self.startapetest(testType=args.t, targetScript=args.s)
  File "/app/utils/testkit.py", line 31, in startapetest
    self.run_test_script(testType=testType,targetScript=targetScript)
  File "/app/utils/testkit.py", line 34, in run_test_script
    with networks.optimism.mainnet_fork.use_default_provider():
  File "/usr/local/lib/python3.9/site-packages/ape/managers/networks.py", line 316, in __getattr
    raise ApeAttributeError(f"{NetworkManager.__name} has no attribute '{attr_name}'.")
ape.exceptions.ApeAttributeError: NetworkManager has no attribute 'optimism'.

```

- the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

`ape networks list`

- full output of the error you received

### How can it be fixed?

Fill this in if you have ideas on how the bug could be fixed.

**Comment by mikeshultz** [comment]
Also seen in one of my PRs on ape-alchemy.  [The CI run fails](https://github.com/ApeWorX/ape-alchemy/actions/runs/8763461680/job/24052485346?pr=67) as if none of the plugins are getting initialized.
